name: skin
channels:
  - simpleitk
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python 3.8
  - pytorch 1.8*
  - torchvision
  - tensorboardx
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - hdbscan
  - pytest
  - pip:
    - -r requirements.txt
